### ISSUE TITLE
Práctica Back End

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-back-end-egal#2]
[Práctica de login para Back-End.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-egal/files/6557594/Practica.de.login.para.Back-End.pdf)

**Comment by MariaC232** [comment]
Calificación: 28%
Buen trabajo

**Comment by josealfredo79** [comment]
Si, esta bien hecho y revisado el trabajo, solo falta la metodología Scrum
